version: '3.8'
services:
    npm:
        build:
            context: .
            dockerfile: ./images/node-app.dockerfile
        entrypoint: ['npm']
        volumes:
            - ./app/node_modules:/app/node_modules
            - ./app/package.json:/app/package.json

    node:
        build:
            context: .
            dockerfile: ./images/node-app.dockerfile
        volumes:
            - ./app/node_modules:/app/node_modules
            - ./app/package.json:/app/package.json
            - ./app/src:/app/src
        ports:
            - 8000:8000
