version: '3.8'
services:
    npm: # utility
        build:
            context: ./app
            dockerfile: Dockerfile
        entrypoint: ['npm']
        volumes:
            - ./app/node_modules:/app/node_modules
            - ./app/package.json:/app/package.json
        env_file:
            - ./envs/node-app.env

    f-npm: # utility
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: builder
        entrypoint: ['npm']
        volumes:
            - ./frontend/node_modules:/app/node_modules
            - ./frontend/package.json:/app/package.json

    node:
        build: ./app
        volumes:
            - node_modules:/app/node_modules
            - ./app/src:/app/src #for development purpose only
        ports:
            - 8000:8000
        env_file:
            - ./envs/node-app.env

    frontend:
        build: ./frontend
        volumes:
            - react_modules:/app/node_modules
        ports:
            - 80:80
        depends_on:
            - node

volumes:
    node_modules:
    react_modules:
