version: '3.8'
services:
    npm: # utility
        build:
            context: ./app
            dockerfile: Dockerfile
        entrypoint: ['npm']
        volumes:
            - ./app/node_modules:/app/node_modules
            - ./app/package.json:/app/package.json
        env_file:
            - ./envs/node-app.env

    f-npm: # utility
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: builder
        entrypoint: ['npm']
        volumes:
            - ./frontend/node_modules:/app/node_modules
            - ./frontend/package.json:/app/package.json
    f-build:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: builder
        entrypoint: ['npm', 'run', 'build']
        volumes:
            - ./frontend/src:/app/src
            - build_app:/app/build
    dev:
        build: ./nginx
        volumes:
            - build_app:/usr/share/nginx/html
        ports:
            - 80:80
        depends_on:
            - node
            - f-build

    node:
        build: ./app
        volumes:
            - node_modules:/app/node_modules
        ports:
            - 8000:8000
        env_file:
            - ./envs/node-app.env

    frontend:
        build: ./frontend
        volumes:
            - react_modules:/app/node_modules
        ports:
            - 80:80
        depends_on:
            - node

volumes:
    node_modules:
    react_modules:
    build_app:
